sudo: false
language: java
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
  
addons:
  sonarqube: true  

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=$SONAR_TOKEN
