sudo: false
language: java

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
  
addons:
  sonarqube:
    organization: "petermcj-github"
    branches:
      - master
      - development

jdk:
 - openjdk7
script:
  - mvn clean verify

after_success:
  - jdk_switcher use oraclejdk8
  - test  $TRAVIS_PULL_REQUEST == "true" && mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.analysis.mode=preview
  - test  $TRAVIS_PULL_REQUEST == "false" && mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN

