sudo: false
language: java
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
addons:
  sonarqube:
    organization: "petermcj-github" 
    token:$SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
